/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_zbar_Image */

#ifndef _Included_net_sourceforge_zbar_Image
#define _Included_net_sourceforge_zbar_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_init
  (JNIEnv *, jclass);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sourceforge_zbar_Image_create
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    convert
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_net_sourceforge_zbar_Image_convert
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    getFormat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sourceforge_zbar_Image_getFormat
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    setFormat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_setFormat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    getSequence
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Image_getSequence
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    setSequence
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_setSequence
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Image_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Image_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    getSize
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_net_sourceforge_zbar_Image_getSize
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    setSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_setSize__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    setSize
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_setSize___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    getCrop
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_net_sourceforge_zbar_Image_getCrop
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    setCrop
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_setCrop__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    setCrop
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_setCrop___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    getData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sourceforge_zbar_Image_getData
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    setData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_setData___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    setData
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Image_setData___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     net_sourceforge_zbar_Image
 * Method:    getSymbols
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_sourceforge_zbar_Image_getSymbols
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_zbar_ImageScanner */

#ifndef _Included_net_sourceforge_zbar_ImageScanner
#define _Included_net_sourceforge_zbar_ImageScanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sourceforge_zbar_ImageScanner
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_ImageScanner_init
  (JNIEnv *, jclass);

/*
 * Class:     net_sourceforge_zbar_ImageScanner
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sourceforge_zbar_ImageScanner_create
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_ImageScanner
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_ImageScanner_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sourceforge_zbar_ImageScanner
 * Method:    setConfig
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_ImageScanner_setConfig
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     net_sourceforge_zbar_ImageScanner
 * Method:    parseConfig
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_ImageScanner_parseConfig
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sourceforge_zbar_ImageScanner
 * Method:    enableCache
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_ImageScanner_enableCache
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     net_sourceforge_zbar_ImageScanner
 * Method:    getResults
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_sourceforge_zbar_ImageScanner_getResults
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sourceforge_zbar_ImageScanner
 * Method:    scanImage
 * Signature: (Lnet/sourceforge/zbar/Image;)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_ImageScanner_scanImage
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_zbar_Symbol */

#ifndef _Included_net_sourceforge_zbar_Symbol
#define _Included_net_sourceforge_zbar_Symbol
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sourceforge_zbar_Symbol_NONE
#define net_sourceforge_zbar_Symbol_NONE 0L
#undef net_sourceforge_zbar_Symbol_PARTIAL
#define net_sourceforge_zbar_Symbol_PARTIAL 1L
#undef net_sourceforge_zbar_Symbol_EAN8
#define net_sourceforge_zbar_Symbol_EAN8 8L
#undef net_sourceforge_zbar_Symbol_UPCE
#define net_sourceforge_zbar_Symbol_UPCE 9L
#undef net_sourceforge_zbar_Symbol_ISBN10
#define net_sourceforge_zbar_Symbol_ISBN10 10L
#undef net_sourceforge_zbar_Symbol_UPCA
#define net_sourceforge_zbar_Symbol_UPCA 12L
#undef net_sourceforge_zbar_Symbol_EAN13
#define net_sourceforge_zbar_Symbol_EAN13 13L
#undef net_sourceforge_zbar_Symbol_ISBN13
#define net_sourceforge_zbar_Symbol_ISBN13 14L
#undef net_sourceforge_zbar_Symbol_I25
#define net_sourceforge_zbar_Symbol_I25 25L
#undef net_sourceforge_zbar_Symbol_DATABAR
#define net_sourceforge_zbar_Symbol_DATABAR 34L
#undef net_sourceforge_zbar_Symbol_DATABAR_EXP
#define net_sourceforge_zbar_Symbol_DATABAR_EXP 35L
#undef net_sourceforge_zbar_Symbol_CODABAR
#define net_sourceforge_zbar_Symbol_CODABAR 38L
#undef net_sourceforge_zbar_Symbol_CODE39
#define net_sourceforge_zbar_Symbol_CODE39 39L
#undef net_sourceforge_zbar_Symbol_PDF417
#define net_sourceforge_zbar_Symbol_PDF417 57L
#undef net_sourceforge_zbar_Symbol_QRCODE
#define net_sourceforge_zbar_Symbol_QRCODE 64L
#undef net_sourceforge_zbar_Symbol_CODE93
#define net_sourceforge_zbar_Symbol_CODE93 93L
#undef net_sourceforge_zbar_Symbol_CODE128
#define net_sourceforge_zbar_Symbol_CODE128 128L
/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Symbol_init
  (JNIEnv *, jclass);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_Symbol_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Symbol_getType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getConfigMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Symbol_getConfigMask
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getModifierMask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Symbol_getModifierMask
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sourceforge_zbar_Symbol_getData
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getDataBytes
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_sourceforge_zbar_Symbol_getDataBytes
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getQuality
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Symbol_getQuality
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Symbol_getCount
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getLocationSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Symbol_getLocationSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getLocationX
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Symbol_getLocationX
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getLocationY
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Symbol_getLocationY
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getOrientation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_Symbol_getOrientation
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    getComponents
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_sourceforge_zbar_Symbol_getComponents
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sourceforge_zbar_Symbol
 * Method:    next
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sourceforge_zbar_Symbol_next
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sourceforge_zbar_SymbolSet */

#ifndef _Included_net_sourceforge_zbar_SymbolSet
#define _Included_net_sourceforge_zbar_SymbolSet
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sourceforge_zbar_SymbolSet_MAX_ARRAY_SIZE
#define net_sourceforge_zbar_SymbolSet_MAX_ARRAY_SIZE 2147483639L
/*
 * Class:     net_sourceforge_zbar_SymbolSet
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_SymbolSet_init
  (JNIEnv *, jclass);

/*
 * Class:     net_sourceforge_zbar_SymbolSet
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_sourceforge_zbar_SymbolSet_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sourceforge_zbar_SymbolSet
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sourceforge_zbar_SymbolSet_size
  (JNIEnv *, jobject);

/*
 * Class:     net_sourceforge_zbar_SymbolSet
 * Method:    firstSymbol
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_sourceforge_zbar_SymbolSet_firstSymbol
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
